title: Another GH Page

description: >- # this means to ignore newlines until "baseurl:"
  My notes and tips.

#baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  redle

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true


theme: jekyll-theme-hacker

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap